bw6761 golang wrapper
celer-network/icicle pull request #2
Opened 2023-09-26 15:18 UTC by ImmanuelSegol

## Describe the changes

This PR...

## Linked Issues

Resolves #

2023-09-27 07:54 UTC, DmytroTym requested changes

2023-09-27 07:54 UTC, DmytroTym commented on icicle/curves/bw6_761/curve_config.cuh
> +#include "../../primitives/extension_field.cuh"
I don't think you nee lines 6-8. I assume they were added to solve a compilation error but the problem was in the other place (in projective.cu). G2 curve isn't over the extension field and we should be able to speed up compilation quite a bit by removing this unnecessary import.

2023-09-27 07:54 UTC, DmytroTym commented on icicle/curves/bw6_761/curve_config.cuh
> +  typedef ExtensionField<PARAMS_BW6_761::fq_config> g2_point_field_t;
This should be removed as well

2023-09-27 07:54 UTC, DmytroTym commented on icicle/utils/sharedmem.cuh
> +__device__ void Error_UnsupportedType()
@vhnatyk pls take a look, is this how `Unresolved extern function '_Z21Error_UnsupportedTypev'` should be resolved? Maybe `#include "../curves/bw6_671/curve_config.cuh"` can help?

2023-09-27 07:54 UTC, DmytroTym commented on goicicle/curves/bw6761/g2.go
> +	X, Y ExtentionField
That's not how G2 works for this curve unfortunately, the coordinates of points are from the same field as G1 points and not extension field elements

2023-09-27 07:54 UTC, DmytroTym commented on goicicle/curves/bw6761/g2.go
> +		Z: ExtentionField{
In principle it's probably better to use functions like [projective_from_affine](https://github.com/ingonyama-zk/icicle/blob/main/icicle/curves/bls12_377/projective.cu#L34) from CUDA, it's better to have a single source of truth. Like in this case, because G2 is actually not over extension field, and the size of limbs is wrong too, this function might work incorrectly

2023-09-27 11:36 UTC, vhnatyk commented on icicle/utils/sharedmem.cuh
> +__device__ void Error_UnsupportedType()
while seems this may trick a linker - for compatibility at least with ntt templates - the file should be extended with like [other curves](https://github.com/celer-network/icicle/blob/03fac235a420d73a40ce79e336e6ac0f6f21486c/icicle/utils/sharedmem.cuh#L260-L277)

2023-09-27 11:40 UTC, vhnatyk commented on icicle/utils/sharedmem.cuh
> +__device__ void Error_UnsupportedType()
like it's 4years+ but seems there is no better workaround for templated dynamic shared memory other than[ Lei Mao blog's](https://leimao.github.io/blog/CUDA-Shared-Memory-Templated-Kernel/)

2023-10-05 11:29 UTC, ImmanuelSegol commented on goicicle/curves/bw6761/g2.go
> +	X, Y ExtentionField
Done

2023-10-05 11:46 UTC, ImmanuelSegol commented on icicle/curves/bw6_761/curve_config.cuh
> +#include "../../primitives/extension_field.cuh"
Done

2023-10-05 11:46 UTC, ImmanuelSegol commented on goicicle/curves/bw6761/g2.go
> +		Z: ExtentionField{
Thanks, this is a left over function that I didnt update.

2023-10-05 11:46 UTC, ImmanuelSegol commented on goicicle/curves/bw6761/g2.go
> +		Z: ExtentionField{
removed it

2023-10-05 11:46 UTC, ImmanuelSegol commented on icicle/curves/bw6_761/curve_config.cuh
> +  typedef ExtensionField<PARAMS_BW6_761::fq_config> g2_point_field_t;
Done, i removed the wrong imports as well from 377

2023-10-05 11:46 UTC, ImmanuelSegol commented on icicle/utils/sharedmem.cuh
> +__device__ void Error_UnsupportedType()
I think this worked, im building it now

2023-10-08 07:22 UTC, DmytroTym requested changes
Good job, I think you're almost done but I'd prefer that you delete newly auto-generated `src/curves/bw6_761.rs` and `src/test_bw6_761.rs`, they don't really work. Rust interface is not an immediate priority with this curve and we should introduce it as we refactor APIs on our feature branch IMO.

2023-10-08 07:22 UTC, DmytroTym commented on icicle/utils/sharedmem.cuh
> +__device__ void Error_UnsupportedType()
But you haven't included `struct SharedMemory<BW6_671::scalar_t> {...}` and `struct SharedMemory<BW6_671::projective_t> {...}`, is it ok? @vhnatyk could you pls take a look again?

2023-10-08 07:22 UTC, DmytroTym commented on icicle/curves/bw6_761/projective.cu
> +           (point2->z == BW6_761::g2_point_field_t::zero()));
Trying to `#include "projective.cu"` leads to a compile error as the compiler doesn't know about `g2_point_field_t` (you deleted it from `curve_config.cuh`). I think you should revert to using `point_field_t` here.

2023-10-08 07:57 UTC, DmytroTym commented on icicle/curves/bw6_761/projective.cu
> +           (point2->z == BW6_761::g2_point_field_t::zero()));
Well not `#include` but rather add to build

2023-10-08 08:07 UTC, vhnatyk commented on goicicle/curves/bw6761/ntt_test.go
> +	assert.Equal(t, nttResult, nttResult)
asserting the equality of the same objects?

2023-10-08 08:11 UTC, vhnatyk commented on icicle/utils/sharedmem.cuh
> +__device__ void Error_UnsupportedType()
> while seems this may trick a linker - for compatibility at least with ntt templates - the file should be extended with like [other curves](https://github.com/celer-network/icicle/blob/03fac235a420d73a40ce79e336e6ac0f6f21486c/icicle/utils/sharedmem.cuh#L260-L277)

@ImmanuelSegol  - this may build with that stub function, but ntt should not pass correctly if shared mem kernel is used

2023-10-08 08:18 UTC, vhnatyk commented on icicle/utils/sharedmem.cuh
> +__device__ void Error_UnsupportedType()
pls remove as it just disables linking error and hides the issue
```
__device__ void Error_UnsupportedType() 
{
    // This function does not need a body, as it's just to throw a linker error.
}
```

and  add the actual implementation like

```
template <>
struct SharedMemory<BW6_671::scalar_t> {
  __device__ BW6_671::scalar_t* getPointer()
  {
    extern __shared__ BW6_671::scalar_t s_scalar_t_bw6_671[];
    return s_scalar_t_bw6_671;
  }
};

template <>
struct SharedMemory<BW6_671::projective_t> {
  __device__ BW6_671::projective_t* getPointer()
  {
    extern __shared__ BW6_671::projective_t s_projective_t_bw6_671[];
    return s_projective_t_bw6_671;
  }
};
#endif //_SHAREDMEM_H_
```

2023-10-08 08:19 UTC, vhnatyk commented on src/curves/mod.rs
> -pub mod bw6_761;
why is it removed?

2023-10-08 08:25 UTC, vhnatyk reviewed
just a few issues in the comments should be addressed,  otherwise looks good 👍🏻

2023-10-08 08:58 UTC, DmytroTym commented on src/curves/mod.rs
> -pub mod bw6_761;
I asked to remove it during the previous review as I removed the (very much incorrectly working) autogenerated Rust wrappers for BW6-671

2023-10-18 01:50 UTC, liuxiaobleach approved these changes

2023-10-18 01:51 UTC, merged